### ISSUE TITLE
Homebrew failed make install on MacOS Monterrey M1

### ISSUE THREAD

**Issue by whoisashking** [yoggy/homebrew-tap#1]
I've been unable to brew install sendosc.  I've clipped the lines below.  I've verified that oscpack is installed.

==> make install
Last 15 lines from /Users/ash/Library/Logs/Homebrew/sendosc/02.make:
/opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -S/tmp/sendosc-20211225-83135-1sktpcy/sendosc-1.0.1 -B/tmp/sendosc-20211225-83135-1sktpcy/sendosc-1.0.1 --check-build-system CMakeFiles/Makefile.cmake 0
/opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -E cmake_progress_start /tmp/sendosc-20211225-83135-1sktpcy/sendosc-1.0.1/CMakeFiles /tmp/sendosc-20211225-83135-1sktpcy/sendosc-1.0.1//CMakeFiles/progress.marks
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/Makefile2 all
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/sendosc.dir/build.make CMakeFiles/sendosc.dir/depend
cd /tmp/sendosc-20211225-83135-1sktpcy/sendosc-1.0.1 && /opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/sendosc-20211225-83135-1sktpcy/sendosc-1.0.1 /tmp/sendosc-20211225-83135-1sktpcy/sendosc-1.0.1 /tmp/sendosc-20211225-83135-1sktpcy/sendosc-1.0.1 /tmp/sendosc-20211225-83135-1sktpcy/sendosc-1.0.1 /tmp/sendosc-20211225-83135-1sktpcy/sendosc-1.0.1/CMakeFiles/sendosc.dir/DependInfo.cmake --color=
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/sendosc.dir/build.make CMakeFiles/sendosc.dir/build
[ 50%] Building CXX object CMakeFiles/sendosc.dir/sendosc.cpp.o
/opt/homebrew/Library/Homebrew/shims/mac/super/clang++  -I/usr/local/include/oscpack -g -Wall -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -MD -MT CMakeFiles/sendosc.dir/sendosc.cpp.o -MF CMakeFiles/sendosc.dir/sendosc.cpp.o.d -o CMakeFiles/sendosc.dir/sendosc.cpp.o -c /tmp/sendosc-20211225-83135-1sktpcy/sendosc-1.0.1/sendosc.cpp
/tmp/sendosc-20211225-83135-1sktpcy/sendosc-1.0.1/sendosc.cpp:8:10: fatal error: 'osc/OscOutboundPacketStream.h' file not found
#include "osc/OscOutboundPacketStream.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/sendosc.dir/sendosc.cpp.o] Error 1
make[1]: *** [CMakeFiles/sendosc.dir/all] Error 2
make: *** [all] Error 2

**Comment by yoggy** [comment]
Thanks for your report.
I finally got my M1 Macbook.
I fixed it. (https://github.com/yoggy/homebrew-tap/commit/d1d85388f97fad69276e936b9f7ac5197def2cb6)
