### ISSUE TITLE
Sending message - Assertion failed - MacOS Monterrey M1

### ISSUE THREAD

**Issue by whoisashking** [yoggy/homebrew-tap#2]
Hello, I'm receiving the following error when sending any message to the Lightform device.  I have verified the IP (redacted) and port manually.

% sendosc xx.xx.xx.xx 8000 /stop
Assertion failed: (sizeof(osc::int32) == 4), function OutboundPacketStream, file OscOutboundPacketStream.cpp, line 166.
zsh: abort      sendosc xx.xx.xx.xx 8000 /stop

**Comment by whoisashking** [comment]
I noticed your earlier commit on oscpack, so I did a brew reinstall.  I no longer see the error.

**Comment by yoggy** [comment]
Please uninstalled oscpack & sendosc first, and then reinstalled it again.

```
$ brew uninstall oscpack sendosc
$ brew install yoggy/tap/sendosc
```

see also... https://github.com/yoggy/homebrew-tap/blob/master/oscpack-arm64.patch
